# Generated by Django 5.0 on 2025-10-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemcategory',
            name='unique_item_category',
        ),
        migrations.RemoveConstraint(
            model_name='itemoption',
            name='unique_item_option',
        ),
        migrations.RenameField(
            model_name='itemcategory',
            old_name='menu_item',
            new_name='menuitem',
        ),
        migrations.RenameField(
            model_name='itemoption',
            old_name='menu_item',
            new_name='menuitem',
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='itemoption',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='option',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('menuitem', 'category'), name='unique_item_category'),
        ),
        migrations.AddConstraint(
            model_name='itemoption',
            constraint=models.UniqueConstraint(fields=('menuitem', 'option'), name='unique_item_option'),
        ),
    ]
